parameters:
    okvpn.config.default_policy: []
    okvpn.config.cron_timezone: null

services:
    okvpn_okvpn.middleware.lock:
        class: Okvpn\Bundle\CronBundle\Middleware\LockMiddlewareEngine
        public: false
        arguments:
            - '@?lock.factory'
        tags:
            - { name: okvpn_cron.middleware, priority: -15 }

    okvpn_cron.middleware.async:
        class: Okvpn\Bundle\CronBundle\Middleware\AsyncProcessEngine
        arguments: [~]
        tags:
            - { name: okvpn_cron.middleware, priority: -5 }
    
    okvpn_cron.checker:
        class: Okvpn\Bundle\CronBundle\Cron\CronChecker

    okvpn_cron.middleware.cron_expression:
        class: Okvpn\Bundle\CronBundle\Middleware\CronMiddlewareEngine
        public: false
        arguments:
            - '@okvpn_cron.checker'
            - '%okvpn.config.cron_timezone%'
            - '@?clock'
            - '@Okvpn\Bundle\CronBundle\Runner\ScheduleLoopInterface'
            - '@Okvpn\Bundle\CronBundle\Runner\TimerStorage'
        tags:
            - { name: okvpn_cron.middleware, priority: 20 }

    okvpn_cron.middleware.execute_service:
        class: Okvpn\Bundle\CronBundle\Middleware\ServiceInvokeEngine
        public: false
        arguments:
            - '@okvpn_cron.commands_locator'
        tags:
            - { name: okvpn_cron.middleware, priority: -30 }

    okvpn_cron.middleware.console_command:
        class: Okvpn\Bundle\CronBundle\Middleware\ConsoleCommandEngine
        arguments: ['@?kernel']
        public: false
        tags:
            - { name: okvpn_cron.middleware, priority: -40 }

    okvpn_cron.middleware.shell:
        class: Okvpn\Bundle\CronBundle\Middleware\ShellInvokeEngine
        public: false
        tags:
            - { name: okvpn_cron.middleware, priority: -50 }

    okvpn_cron.middleware.execute_commands:
        class: Okvpn\Bundle\CronBundle\Middleware\CommandRunnerEngine
        public: false
        arguments:
            - '@okvpn_cron.commands_locator'
        tags:
            - { name: okvpn_cron.middleware, priority: -20 }

    okvpn_cron.commands_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        public: false
        arguments:
            - []
        tags:
            - { name: container.service_locator }

    okvpn_cron.schedule_factory:
        class: Okvpn\Bundle\CronBundle\Loader\ScheduleFactory
        arguments: [[], []]

    okvpn_cron.array_loader:
        class: Okvpn\Bundle\CronBundle\Loader\ArrayScheduleLoader
        public: false
        arguments:
            - ~
            - '@okvpn_cron.schedule_factory'
        tags:
            - { name: okvpn_cron.loader }

    okvpn_cron.loader_default:
        class: Okvpn\Bundle\CronBundle\Loader\ScheduleLoader
        arguments:
            - !tagged okvpn_cron.loader

    okvpn_cron.runner_default:
        class: Okvpn\Bundle\CronBundle\Runner\ScheduleRunner
        arguments:
            - !tagged okvpn_cron.middleware

    Okvpn\Bundle\CronBundle\Runner\TimerStorage: ~

    okvpn_cron.standalone_loop:
        class: Okvpn\Bundle\CronBundle\Runner\StandaloneLoop
        arguments:
            - '@?clock'
            - '%okvpn.config.cron_timezone%'

    okvpn_cron.react_loop:
        class: Okvpn\Bundle\CronBundle\React\ReactLoopAdapter
        arguments: [~, '%okvpn.config.cron_timezone%']
    
    Okvpn\Bundle\CronBundle\Runner\ScheduleLoopInterface:
        alias: okvpn_cron.standalone_loop

    Okvpn\Bundle\CronBundle\React\ReactLoopAdapter:
        arguments:
            - ~
            - '%okvpn.config.cron_timezone%'

    Okvpn\Bundle\CronBundle\Command\CronCommand:
        arguments:
            - '@okvpn_cron.runner_default'
            - '@okvpn_cron.loader_default'
            - '@?event_dispatcher'
            - '@Okvpn\Bundle\CronBundle\Runner\ScheduleLoopInterface'
            - '@?clock'
            - '%okvpn.config.cron_timezone%'
        tags:
            - { name: console.command }

    Okvpn\Bundle\CronBundle\Command\CronDebugCommand:
        arguments:
            - '@okvpn_cron.runner_default'
            - '@okvpn_cron.loader_default'
        tags:
            - { name: console.command }

    Okvpn\Bundle\CronBundle\Command\CronExecuteCommand:
        arguments:
            - '@okvpn_cron.runner_default'
        tags:
            - { name: console.command }
